apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers: 
      - name: my-app
        image: hamza789/cicd:CICD
        ports:
        - containerPort: 8080
#---
#apiVersion: v1
#kind: Service
#metadata: production
#  name: my-app-service
#  namespace: 
#spec:
#  selector:
#    app: my-app
#  type: LoadBalancer
#  ports:
#  - name: http
#    port: 8080
#    targetPort: 8080